#!/bin/bash

set -e

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

log_info() { echo -e "${BLUE}[INFO]${NC} $1"; }
log_success() { echo -e "${GREEN}[OK]${NC} $1"; }
log_warning() { echo -e "${YELLOW}[WARN]${NC} $1"; }
log_error() { echo -e "${RED}[ERROR]${NC} $1"; }

echo -e "${BLUE}"
echo "╔═══════════════════════════════════════════════════════════╗"
echo "║       Command Center - Production Deployment              ║"
echo "╚═══════════════════════════════════════════════════════════╝"
echo -e "${NC}"
 
SERVER_DOMAIN="dashboard.roboteye.ai"
MASTER_PASSWORD="TurkAI2026"
SSL_EMAIL="furkan.cam@turkai.com"
DB_NAME="command_center"
DB_USER="postgres"
DB_PASSWORD="${MASTER_PASSWORD}_db"
MINIO_ACCESS_KEY="minioadmin"
MINIO_SECRET_KEY="${MASTER_PASSWORD}_minio"
MQTT_USERNAME="TurkAI"
MQTT_PASSWORD="TurkAI"
JWT_SECRET=$(openssl rand -hex 32)
ADMIN_PASSWORD="admin123"

log_info "Sistem bağımlılıkları kontrol ediliyor..."

if ! command -v docker &> /dev/null; then
    log_info "Docker kuruluyor..."
    curl -fsSL https://get.docker.com | sh
    systemctl enable docker
    systemctl start docker
    log_success "Docker kuruldu"
else
    log_success "Docker zaten kurulu"
fi

if ! docker compose version &> /dev/null; then
    log_info "Docker Compose kuruluyor..."
    apt-get update
    apt-get install -y docker-compose-plugin
    log_success "Docker Compose kuruldu"
else
    log_success "Docker Compose zaten kurulu"
fi

if ! command -v python3 &> /dev/null; then
    log_info "Python3 kuruluyor..."
    apt-get update
    apt-get install -y python3 python3-pip python3-venv
    log_success "Python3 kuruldu"
else
    log_success "Python3 zaten kurulu"
fi

log_info ".env dosyası oluşturuluyor..."

cat > .env << EOF
# Command Center Production Configuration
# Generated by deploy.sh on $(date)

# Domain
SERVER_DOMAIN=${SERVER_DOMAIN}

# Database
DB_HOST=postgres
DB_PORT=5432
DB_NAME=${DB_NAME}
DB_USER=${DB_USER}
DB_PASSWORD=${DB_PASSWORD}

# MinIO
MINIO_ENDPOINT=minio:9000
MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
MINIO_SECURE=false
MINIO_BUCKET_IMAGES=images
MINIO_BUCKET_LOGS=logs

# MQTT
MQTT_BROKER=mosquitto
MQTT_PORT=1883
MQTT_USERNAME=${MQTT_USERNAME}
MQTT_PASSWORD=${MQTT_PASSWORD}
MQTT_TLS_ENABLED=false

# JWT
JWT_SECRET_KEY=${JWT_SECRET}
JWT_ALGORITHM=HS256
JWT_EXPIRE_MINUTES=10080
JWT_REFRESH_EXPIRE_DAYS=30

# API
API_HOST=0.0.0.0
API_PORT=8000
ENVIRONMENT=production
DEBUG=false

# CORS
CORS_ORIGINS=https://${FRONTEND_DOMAIN},https://${SERVER_DOMAIN},http://localhost:3000
EOF

log_success ".env dosyası oluşturuldu"
log_info "Dizin yapısı oluşturuluyor..."
mkdir -p docker/mosquitto
mkdir -p docker/nginx
mkdir -p docker/certs/live/${SERVER_DOMAIN}
mkdir -p logs
log_success "Dizin yapısı oluşturuldu"
log_info "Mosquitto şifre dosyası oluşturuluyor..."
docker run --rm -v "$(pwd)/docker/mosquitto:/mosquitto/config" \
    eclipse-mosquitto:2 \
    mosquitto_passwd -b -c /mosquitto/config/passwd ${MQTT_USERNAME} ${MQTT_PASSWORD}

log_success "Mosquitto şifre dosyası oluşturuldu"
log_info "Firewall yapılandırılıyor..."

if command -v ufw &> /dev/null; then
    ufw allow 22/tcp comment "SSH"
    ufw allow 80/tcp comment "HTTP"
    ufw allow 443/tcp comment "HTTPS"
    ufw allow 8883/tcp comment "MQTT TLS"
    ufw --force enable
    log_success "Firewall yapılandırıldı"
fi

CERT_DIR="./docker/certs/live/${SERVER_DOMAIN}"

if [ ! -f "$CERT_DIR/fullchain.pem" ]; then
    log_info "SSL Bootstrapping: Dummy sertifika oluşturuluyor..."
    openssl req -x509 -nodes -newkey rsa:2048 -days 1 \
        -keyout "$CERT_DIR/privkey.pem" \
        -out "$CERT_DIR/fullchain.pem" \
        -subj "/CN=localhost"
    log_success "Dummy sertifika oluşturuldu"
fi

log_info "Docker containerları başlatılıyor..."
docker compose build --no-cache
docker compose up -d postgres minio mosquitto
log_success "Temel servisler başlatıldı"
log_info "Servislerin hazır olması bekleniyor..."
sleep 10
log_info "Veritabanı kontrol ediliyor..."

for i in {1..30}; do
    if docker compose exec -T postgres pg_isready -U ${DB_USER} &> /dev/null; then
        log_success "PostgreSQL hazır"
        break
    fi
    sleep 2
done

log_info "Admin kullanıcısı oluşturuluyor..."

ADMIN_HASH=$(docker compose exec -T postgres sh -c "apt-get update -qq && apt-get install -qq -y python3 python3-pip > /dev/null 2>&1; pip3 install -qq 'passlib[bcrypt]==1.7.4' 'bcrypt==4.0.1' > /dev/null 2>&1; python3 -c \"from passlib.context import CryptContext; print(CryptContext(schemes=['bcrypt'], deprecated='auto').hash('${ADMIN_PASSWORD}'))\"" 2>/dev/null || echo "")

if [ -z "$ADMIN_HASH" ]; then
    ADMIN_HASH='$2b$12$3Tt1LFmbVAjqdIqwbNYLhutJpAMgpjLsWQPE1L6UunXb4eI4ajBwu'
fi

docker compose exec -T postgres psql -U ${DB_USER} -d ${DB_NAME} -c "
INSERT INTO users (username, email, password_hash, role, is_active)
VALUES ('admin', 'admin@${SERVER_DOMAIN}', '${ADMIN_HASH}', 'admin', TRUE)
ON CONFLICT (username) DO UPDATE SET password_hash = '${ADMIN_HASH}';
" 2>/dev/null || log_warning "Admin kullanıcısı zaten mevcut veya init.sql ile oluşturuldu"

log_success "Admin kullanıcısı hazır (admin / ${ADMIN_PASSWORD})"
log_info "MinIO bucket'ları oluşturuluyor..."
sleep 5
docker run --rm --network command_center_app_network minio/mc \
    alias set myminio http://minio:9000 ${MINIO_ACCESS_KEY} "${MINIO_SECRET_KEY}" 2>/dev/null || true

for bucket in images logs processed data-lake detections; do
    docker run --rm --network command_center_app_network minio/mc \
        mb myminio/${bucket} --ignore-existing 2>/dev/null || true
done

log_success "MinIO bucket'ları oluşturuldu"
log_info "Tüm servisler başlatılıyor..."
docker compose up -d
log_success "Tüm containerlar başlatıldı"
log_info "SSL sertifikası alınıyor..."

docker compose run --rm certbot certonly \
    --webroot \
    --webroot-path=/var/www/certbot \
    -d ${SERVER_DOMAIN} \
    --email ${SSL_EMAIL} \
    --agree-tos \
    --non-interactive 2>/dev/null || log_warning "SSL sertifikası alınamadı, dummy sertifika kullanılıyor"

docker compose exec -T nginx nginx -s reload 2>/dev/null || true
log_success "SSL yapılandırması tamamlandı"
log_info "Servis sağlık kontrolü yapılıyor..."
sleep 5

services=("postgres" "minio" "mosquitto" "backend" "nginx")
for service in "${services[@]}"; do
    if docker compose ps | grep -q "${service}.*Up"; then
        log_success "${service} çalışıyor"
    else
        log_warning "${service} çalışmıyor"
    fi
done

echo ""
echo -e "${GREEN}"
echo "╔═══════════════════════════════════════════════════════════╗"
echo "║            Deployment Başarıyla Tamamlandı!               ║"
echo "╚═══════════════════════════════════════════════════════════╝"
echo -e "${NC}"
echo ""
echo " Sunucu Bilgileri:"
echo "   ─────────────────────────────────────────────"
echo "   Frontend:  https://${FRONTEND_DOMAIN}"
echo "   API:       https://${SERVER_DOMAIN}/api/"
echo "   MinIO:     https://${SERVER_DOMAIN}:9001"
echo "   MQTT:      ${SERVER_DOMAIN}:8883"
echo "   ─────────────────────────────────────────────"
echo ""
echo " Admin Giriş Bilgileri:"
echo "   ─────────────────────────────────────────────"
echo "   Username: admin"
echo "   Password: ${ADMIN_PASSWORD}"
echo "   ─────────────────────────────────────────────"
echo ""
echo " Hub .env.local Konfigürasyonu:"
echo "   ─────────────────────────────────────────────"
echo "   MQTT_BROKER=${SERVER_DOMAIN}"
echo "   MQTT_PORT=8883"
echo "   MQTT_USERNAME=${MQTT_USERNAME}"
echo "   MQTT_PASSWORD=${MQTT_PASSWORD}"
echo "   MQTT_TLS_ENABLED=true"
echo "   MQTT_TLS_INSECURE=true"
echo "   ─────────────────────────────────────────────"
echo ""
echo " Yararlı Komutlar:"
echo "   docker compose logs -f        # Tüm logları izle"
echo "   docker compose logs -f backend # Backend logları"
echo "   docker compose ps             # Container durumları"
echo "   docker compose restart        # Tüm servisleri yeniden başlat"
echo "   docker compose down           # Tüm servisleri durdur"
echo ""
log_success "Deployment tamamlandı!"
